import type { DocModel, DocTable } from './document';

const dateOf = (iso: string) => new Date(iso).toLocaleString(undefined, { dateStyle: 'long', timeStyle: 'short' });

// --- Markdown ------------------------------------------------------------------

const mdCell = (v: string) => (v || ' ').replace(/\|/g, '\\|').replace(/\r?\n/g, '<br>');

function mdTable(t: DocTable): string {
  const out: string[] = [];
  if (t.title) out.push(`### ${t.title}`, '');
  if (t.note) out.push(`_${t.note}_`, '');
  out.push(`| ${t.columns.map(mdCell).join(' | ')} |`, `| ${t.columns.map(() => '---').join(' | ')} |`);
  for (const r of t.rows) out.push(`| ${r.map(mdCell).join(' | ')} |`);
  out.push('');
  return out.join('\n');
}

/** Markdown document. `image` is the file name (or data URL) of the diagram picture. */
export function toMarkdown(doc: DocModel, image?: string): string {
  const out: string[] = [`# ${doc.title}`, ''];
  if (doc.description) out.push(doc.description, '');
  out.push(`_Generated by InfraCanvas on ${dateOf(doc.generatedAt)}._`, '');
  for (const s of doc.sections) {
    out.push(`## ${s.title}`, '');
    if (s.intro) out.push(s.intro, '');
    if (s.facts) {
      for (const f of s.facts) out.push(`- **${f.label}:** ${f.value}`);
      out.push('');
    }
    if (s.image) out.push(image ? `![Diagram of ${doc.title}](${image})` : '_The diagram is empty._', '');
    for (const t of s.tables) out.push(mdTable(t));
    if (!s.facts && !s.image && !s.tables.length && s.empty) out.push(`_${s.empty}_`, '');
  }
  return out.join('\n').replace(/\n{3,}/g, '\n\n');
}

// --- HTML ----------------------------------------------------------------------

const esc = (v: string) => v.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const anchor = (id: string) => `s-${id}`;

const SEVERITY = new Set(['error', 'warning', 'info']);
const ACTIONS = new Set(['allow', 'deny', 'allow (disabled)', 'deny (disabled)']);

function htmlCell(v: string, col: string): string {
  if (col === 'Severity' && SEVERITY.has(v)) return `<td><span class="tag ${v}">${esc(v)}</span></td>`;
  if (col === 'Action' && ACTIONS.has(v)) return `<td><span class="tag ${v.split(' ')[0]}">${esc(v)}</span></td>`;
  const mono = ['Address', 'Addresses', 'Subnet', 'Gateway', 'Port', 'Ports', 'VLANs', 'ID', '#'].includes(col);
  return `<td${mono ? ' class="mono"' : ''}>${esc(v)}</td>`;
}

function htmlTable(t: DocTable): string {
  return [
    t.title ? `<h3>${esc(t.title)}</h3>` : '',
    t.note ? `<p class="note">${esc(t.note)}</p>` : '',
    '<div class="table"><table><thead><tr>',
    ...t.columns.map((c) => `<th>${esc(c)}</th>`),
    '</tr></thead><tbody>',
    ...t.rows.map((r) => `<tr>${r.map((v, i) => htmlCell(v, t.columns[i])).join('')}</tr>`),
    '</tbody></table></div>',
  ].join('');
}

const STYLE = `
:root{--fg:#0f172a;--muted:#475569;--subtle:#64748b;--line:#e2e8f0;--soft:#f1f5f9;--accent:#2563eb;--bg:#fff}
@media (prefers-color-scheme:dark){:root:not([data-theme=light]){--fg:#e2e8f0;--muted:#a3b0c2;--subtle:#8291a6;--line:#263247;--soft:#162033;--accent:#60a5fa;--bg:#0b1120}}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--fg);font:14px/1.55 system-ui,-apple-system,"Segoe UI",Roboto,sans-serif}
main{max-width:1180px;margin:0 auto;padding:48px 24px 80px}
header{border-bottom:2px solid var(--fg);padding-bottom:16px;margin-bottom:24px}
h1{font-size:30px;line-height:1.15;margin:0 0 6px;letter-spacing:-.01em}
header p{margin:4px 0;color:var(--muted)}
nav{display:flex;flex-wrap:wrap;gap:4px 16px;margin:0 0 32px;font-size:13px}
nav a{color:var(--accent);text-decoration:none}
nav a:hover{text-decoration:underline}
section{margin:0 0 40px}
h2{font-size:20px;margin:0 0 12px;padding-bottom:6px;border-bottom:1px solid var(--line)}
h3{font-size:14.5px;margin:22px 0 6px}
p.note,p.intro,p.empty{color:var(--muted);margin:4px 0 10px}
p.empty{font-style:italic}
dl{display:grid;grid-template-columns:repeat(auto-fill,minmax(150px,1fr));gap:10px;margin:0}
dl div{border:1px solid var(--line);border-radius:8px;padding:10px 12px}
dt{font-size:12px;color:var(--subtle)}
dd{margin:2px 0 0;font-size:18px;font-weight:600}
figure{margin:0;border:1px solid var(--line);border-radius:8px;overflow:hidden}
figure img{display:block;width:100%;height:auto}
.table{overflow-x:auto}
table{border-collapse:collapse;width:100%;font-size:12.5px}
th{text-align:left;font-weight:600;color:var(--muted);background:var(--soft);padding:6px 8px;border-bottom:1px solid var(--line);white-space:nowrap}
td{padding:5px 8px;border-bottom:1px solid var(--line);vertical-align:top}
td.mono{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:12px;white-space:nowrap}
.tag{display:inline-block;border-radius:4px;padding:0 6px;font-size:11px;font-weight:600;text-transform:capitalize}
.tag.error,.tag.deny{background:#ef44441f;color:#dc2626}.tag.warning{background:#f59e0b24;color:#b45309}.tag.info{background:#3b82f61f;color:#2563eb}.tag.allow{background:#10b9811f;color:#059669}
footer{color:var(--subtle);font-size:12px;border-top:1px solid var(--line);padding-top:12px}
@media print{main{max-width:none;padding:0}nav{display:none}section{break-inside:auto}h2,h3{break-after:avoid}tr{break-inside:avoid}figure{break-inside:avoid}:root{--bg:#fff;--fg:#000}}
`;

/** Self-contained HTML document (diagram embedded); print it to get a PDF. */
export function toHtml(doc: DocModel, image?: string): string {
  const sections = doc.sections
    .map((s) => {
      const parts = [`<section id="${anchor(s.id)}"><h2>${esc(s.title)}</h2>`];
      if (s.intro) parts.push(`<p class="intro">${esc(s.intro)}</p>`);
      if (s.facts) parts.push(`<dl>${s.facts.map((f) => `<div><dt>${esc(f.label)}</dt><dd>${esc(f.value)}</dd></div>`).join('')}</dl>`);
      if (s.image) parts.push(image ? `<figure><img src="${image}" alt="Diagram of ${esc(doc.title)}"></figure>` : '<p class="empty">The diagram is empty.</p>');
      for (const t of s.tables) parts.push(htmlTable(t));
      if (!s.facts && !s.image && !s.tables.length && s.empty) parts.push(`<p class="empty">${esc(s.empty)}</p>`);
      parts.push('</section>');
      return parts.join('');
    })
    .join('\n');
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(doc.title)} — infrastructure documentation</title>
<style>${STYLE}</style>
</head>
<body>
<main>
<header><h1>${esc(doc.title)}</h1>${doc.description ? `<p>${esc(doc.description)}</p>` : ''}<p>Infrastructure documentation · ${esc(dateOf(doc.generatedAt))}</p></header>
<nav aria-label="Contents">${doc.sections.map((s) => `<a href="#${anchor(s.id)}">${esc(s.title)}</a>`).join('')}</nav>
${sections}
<footer>Generated by InfraCanvas from the project diagram.</footer>
</main>
</body>
</html>
`;
}
